stages:
  - ci-img
  - build
  - test
  - deploy

ci-img:
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: ci-img
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context=$CI_PROJECT_DIR --dockerfile=$CI_PROJECT_DIR/Dockerfile --target=base --verbosity=warn --destination=$CI_REGISTRY_IMAGE/ci:base
  rules:
    - if: "$CI_MERGE_REQUEST_IID == null"
      changes:
        - Dockerfile
        - .gitlab-ci.yml
      when: always

build:linux:
  stage: build
  tags:
    - docker
  image:
    name: $CI_REGISTRY_IMAGE/ci:base
    entrypoint: [""]
  script:
    - mkdir -p /cache/decker
    - STACK_ROOT=/cache/decker make clean-build
    - cp $(STACK_ROOT=/cache/decker stack path | grep "local-install-root" | awk '{printf "%s/bin/decker",$2}') decker
  artifacts:
    paths:
      - decker
  cache:
    key: stack_work
    paths:
      - .stack-work
  interruptible: true

build:mac:
  tags:
    - mac
  stage: build
  script:
    - brew upgrade node
    - git rev-parse --short HEAD
    - make clean-build
    - cp $(stack path | grep "local-install-root" | awk '{printf "%s/bin/decker",$2}') decker
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .stack-work
  artifacts:
    paths:
      - decker
  when: always
  interruptible: true
  needs: []

build:win:
  tags:
    - win
  stage: build
  script:
    - '&.\bin\build.ps1 standalone -preparepackage'
  artifacts:
    paths:
      - decker.exe
      - version.txt
  cache:
    key: build-win
    paths:
      - .stack-work
  when: always
  interruptible: true
  needs: []

test:linux:
  stage: test
  tags:
    - docker
  image:
    name: $CI_REGISTRY_IMAGE/ci:base
    entrypoint: [""]
  script:
    - STACK_ROOT=/cache/decker make test
  cache:
    key: stack_work
    paths:
      - .stack-work
  needs:
    - job: build:linux
  interruptible: true

test:mac:
  stage: test
  tags:
    - mac
  script:
    - make test
  cache:
    key: stack_work
    paths:
      - .stack-work
  needs:
    - job: build:mac
  interruptible: true

test:win:
  tags:
    - win
  stage: test
  script:
    - "& stack test -j1"
  cache:
    key: test-win
    paths:
      - .stack-work
  when: always
  needs:
    - job: build:win
  interruptible: true

deploy:mac:
  stage: deploy
  image:
    name: minio/mc:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  script:
    - if [ $CI_COMMIT_REF_NAME == "master" ]; then SUFFIX="-nightly"; else SUFFIX="-release"; fi
    - mc config host add store http://store.hci.informatik.uni-wuerzburg.de:9002 $MINIO_ACCESS $MINIO_SECRET --api S3v4
    - mc cp ./decker store/decker/decker-mac${SUFFIX}
  needs:
    - job: build:mac
      artifacts: true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - if: '$CI_COMMIT_REF_NAME =~ /^v\d\.\d\.\d-patching$/'
      when: always
  interruptible: true
  resource_group: deploy_mac

deploy:linux:
  stage: deploy
  image:
    name: minio/mc:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  script:
    - if [ $CI_COMMIT_REF_NAME == "master" ]; then SUFFIX="-nightly"; else SUFFIX="-release"; fi
    - mc config host add store http://store.hci.informatik.uni-wuerzburg.de:9002 $MINIO_ACCESS $MINIO_SECRET --api S3v4
    - mc cp ./decker store/decker/decker-linux${SUFFIX}
  needs:
    - job: build:linux
      artifacts: true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - if: '$CI_COMMIT_REF_NAME =~ /^v\d\.\d\.\d-patching$/'
      when: always
  interruptible: true
  resource_group: deploy_linux

deploy:docker:
  stage: deploy
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context=$CI_PROJECT_DIR --dockerfile=$CI_PROJECT_DIR/Dockerfile-prebuilt --verbosity=warn --destination=$CI_REGISTRY_IMAGE:latest
  needs:
    - job: build:linux
      artifacts: true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - if: '$CI_COMMIT_REF_NAME =~ /^v\d\.\d\.\d-patching$/'
      when: always
  interruptible: true

deploy:win:
  stage: deploy
  image:
    name: minio/mc:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  script:
    - if [ $CI_COMMIT_REF_NAME == "master" ]; then SUFFIX="-nightly"; else SUFFIX="-release"; fi
    - mc config host add store http://store.hci.informatik.uni-wuerzburg.de:9002 $MINIO_ACCESS $MINIO_SECRET --api S3v4
    - mc cp ./decker.exe store/decker/decker-win${SUFFIX}.exe
    - mc cp ./version.txt store/decker/version-win${SUFFIX}.txt
  needs:
    - job: build:win
      artifacts: true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - if: '$CI_COMMIT_REF_NAME =~ /^v\d\.\d\.\d-patching$/'
      when: always
  interruptible: true
  resource_group: deploy_win
