on:
  push:
    tags:
      - "v**"

name: Build Release
jobs:
  build-all-platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Decker ${{ github.ref_name }} (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.0.2"
          enable-stack: true
          stack-no-global: true
          stack-version: "latest"
          stack-setup-ghc: true

      - name: Build & test
        run: |
          stack test
          stack --local-bin-path=dist install

      - name: Rename executable
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          mv dist/decker "dist/decker-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}"

      - name: Rename executable
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          mv dist/decker.exe "dist/decker-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}.exe"

      - name: Release
        uses: "softprops/action-gh-release@v1"
        with:
          name: 'Decker ${{ github.ref_name }}'
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: true
          files: | 
            readme.md
            changelog.md
            dist/**
